name: neurogram

services:
  postgres:
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:?set DB_USER in .env}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?set DB_PASSWORD in .env}
      POSTGRES_DB: ${DB_NAME:?set DB_NAME in .env}
    # noinspection ComposeUnknownValues
    ports:
      - "${DB_IP:?set DB_IP in .env}:${DB_PORT:?set DB_PORT in .env}:5432"
    volumes:
      - pg-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    # noinspection ComposeUnknownValues
    ports:
      - "${REDIS_HOST:?set REDIS_HOST in .env}:${REDIS_PORT:?set REDIS_PORT in .env}:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg-data:
  redis-data: